# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('icon.ico', '.')],
    hiddenimports=[
        'faster_whisper',
        'pyaudiowpatch',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.sip',
        'numpy',
        'huggingface_hub',
        'tokenizers',
        'onnxruntime',
        'transformers',
        'transformers.utils.versions',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 'torchvision', 'torchaudio',
        'scipy', 'scipy.linalg', 'scipy.special', 'scipy.sparse',
        'pandas', 'matplotlib', 'PIL', 'Pillow',
        'tensorflow', 'tensorboard',
        'notebook', 'IPython', 'ipykernel', 'jupyter',
        'pytest', 'unittest', 'doctest',
        'tkinter', 'tcl', 'tk',
        'lib2to3',
        'boto3', 'botocore', 's3transfer',
        'sphinx', 'docutils',
        'uvicorn', 'starlette', 'fastapi',
        'pygments', 'rich',
        'transformers',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='OpenCaptions',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)
